enum actionsTypes {
  SAVE_EMAIL = "SAVE_EMAIL",
  SEND_EXPENSES = "SEND_EXPENSES",
  DELETE_EXPENSES = "DELETE_EXPENSES",
  EDIT_VALUE = "EDIT_VALUE",
  SEND_EDITED_VALUE = "SEND_EDITED_VALUE",
}

export default actionsTypes;
